services:
  php:
    build:
      context: ./docker/php
    container_name: symfony_php
    working_dir: /var/www/html
    volumes:
      - .:/var/www/html
    command: ["sh", "-c", "composer install && npm install && npm run build && php-fpm"]
    depends_on:
      - mysql
    environment:
      - DATABASE_URL=mysql://root:root@mysql:3306/symfony_db

  nginx:
    image: nginx:latest
    container_name: symfony_nginx
    ports:
      - "80:80"
    volumes:
      - .:/var/www/html
      - ./docker/nginx/default.conf:/etc/nginx/conf.d/default.conf
    depends_on:
      - php

  mysql:
    image: mysql:8.0
    container_name: symfony_mysql
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: kobizo_test
      MYSQL_USER: vinhpt
      MYSQL_PASSWORD: 160399
    ports:
      - "3306:3306"
    volumes:
      - mysql_data:/var/lib/mysql

  phpmyadmin:
    image: phpmyadmin/phpmyadmin
    container_name: symfony_phpmyadmin
    restart: always
    environment:
      PMA_HOST: mysql
      MYSQL_ROOT_PASSWORD: root
    ports:
      - "8080:80"
    depends_on:
      - mysql

volumes:
  mysql_data:
