app_frontend:
    path: /{vueRouting}
    controller: Symfony\Bundle\FrameworkBundle\Controller\TemplateController::templateAction
    defaults:
        template: 'base.html.twig'
    requirements:
        vueRouting: "^(?!api).+" # Bỏ qua các route API

index:
   path: /
   controller: App\Controller\DefaultController::index

create:
   path: /api/posts
   controller: App\Controller\PostController::create
   methods: POST




